[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# ファイル拡張子の設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

# フォーム送信設定（Netlify Forms使用）
[[redirects]]
  from = "/contact-form.php"
  to = "/.netlify/functions/contact-form"
  status = 200